const articles=[
{title:'How to Choose the Right Motor Control Solution for Your Facility',category:'Motor control',date:'2026-01-12',excerpt:'A practical guide to VFDs, starters, contactors and overload protection for dependable industrial operation.'},
{title:'Power Distribution Fundamentals for Commercial Buildings',category:'Power distribution',date:'2026-01-28',excerpt:'The key components and planning considerations behind safe, resilient building power infrastructure.'},
{title:'PLC, HMI and SCADA: Understanding the Automation Stack',category:'Industrial automation',date:'2026-02-09',excerpt:'Learn how core automation technologies work together to improve visibility, control and productivity.'},
{title:'What to Include in an Industrial Component Enquiry',category:'Procurement',date:'2026-02-19',excerpt:'A concise checklist for helping suppliers return accurate quotations faster.'},
{title:'VFD Selection: Five Specifications That Matter',category:'Motor control',date:'2026-03-03',excerpt:'Frequency range, load profile, environment and more: the details that shape a reliable drive choice.'},
{title:'Reducing Procurement Risk in Electrical Projects',category:'Project support',date:'2026-03-17',excerpt:'How structured sourcing, documentation and supplier coordination can protect project timelines.'},
{title:'Industrial Automation Trends for Growing Manufacturers',category:'Industry insight',date:'2026-04-02',excerpt:'A forward-looking view of connected control, data visibility and practical digital adoption.'},
{title:'Switchgear and Protection: A Buyer’s Quick Guide',category:'Electrical components',date:'2026-04-16',excerpt:'Understand the role of protection equipment and the questions to ask before ordering.'},
{title:'How IMS and CRM Tools Improve B2B Operations',category:'Business technology',date:'2026-05-01',excerpt:'Connecting stock, enquiries and customer relationships gives industrial businesses a clearer operating picture.'},
{title:'Building Better Long-Term Supplier Partnerships',category:'B2B strategy',date:'2026-05-18',excerpt:'The practical habits that create stronger communication, better planning and more dependable supply.'}
];
const menu=document.querySelector('.menu-toggle'),links=document.querySelector('.nav-links');if(menu&&links){menu.addEventListener('click',()=>{const open=links.classList.toggle('open');menu.setAttribute('aria-expanded',open)});links.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>links.classList.remove('open')))}
const observer=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(e=>observer.observe(e));
const grid=document.querySelector('#articleGrid'),search=document.querySelector('#articleSearch'),empty=document.querySelector('#emptyState');function renderArticles(){if(!grid)return;const q=(search?.value||'').toLowerCase().trim();const list=articles.filter(a=>(a.title+' '+a.category+' '+a.excerpt).toLowerCase().includes(q));grid.innerHTML=list.map(a=>`<article class="article-card reveal visible"><div class="tag">${a.category}</div><h2>${a.title}</h2><time datetime="${a.date}">${new Date(a.date+'T00:00:00').toLocaleDateString('en-GB',{day:'numeric',month:'long',year:'numeric'})}</time><p>${a.excerpt}</p><a class="text-link" href="mailto:Maksud.mr@gmail.com?subject=${encodeURIComponent(a.title)}">Discuss this topic →</a></article>`).join('');if(empty)empty.hidden=list.length>0}if(search)search.addEventListener('input',renderArticles);renderArticles();
